src/Entity/MappedMatch.php
<?php

namespace App\Entity;

class MappedMatch
{
    /**
     * @var int
     */
    protected $smiteMatchId;

    /**
     * @var MatchPlayer[]
     */
    protected $matchPlayers = [];

    /**
     * @var string
     */
    protected $matchType;

    /**
     * @var int
     */
    protected $minutes;

    /**
     * @var int
     */
    protected $winningTaskforce;

    /**
     * @var \DateTime
     */
    protected $date;

    /**
     * @return int
     */
    public function getSmiteMatchId(): int
    {
        return $this->smiteMatchId;
    }

    /**
     * @param int $smiteMatchId
     * @return MappedMatch
     */
    public function setSmiteMatchId(int $smiteMatchId): MappedMatch
    {
        $this->smiteMatchId = $smiteMatchId;
        return $this;
    }

    /**
     * @return MatchPlayer[]
     */
    public function getMatchPlayers(): array
    {
        return $this->matchPlayers;
    }

    /**
     * @param MatchPlayer[] $matchPlayers
     * @return MappedMatch
     */
    public function setMatchPlayers(array $matchPlayers): MappedMatch
    {
        $this->matchPlayers = $matchPlayers;
        return $this;
    }

    /**
     * @return string
     */
    public function getMatchType(): string
    {
        return $this->matchType;
    }

    /**
     * @param string $matchType
     * @return MappedMatch
     */
    public function setMatchType(string $matchType): MappedMatch
    {
        $this->matchType = $matchType;
        return $this;
    }

    /**
     * @return int
     */
    public function getMinutes(): int
    {
        return $this->minutes;
    }

    /**
     * @param int $minutes
     * @return MappedMatch
     */
    public function setMinutes(int $minutes): MappedMatch
    {
        $this->minutes = $minutes;
        return $this;
    }

    /**
     * @return int
     */
    public function getWinningTaskforce(): int
    {
        return $this->winningTaskforce;
    }

    /**
     * @param int $winningTaskforce
     * @return MappedMatch
     */
    public function setWinningTaskforce(int $winningTaskforce): MappedMatch
    {
        $this->winningTaskforce = $winningTaskforce;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDate(): \DateTime
    {
        return $this->date;
    }

    /**
     * @param \DateTime $date
     * @return MappedMatch
     */
    public function setDate(\DateTime $date): MappedMatch
    {
        $this->date = $date;
        return $this;
    }

    /**
     * @return MatchPlayer[][]
     */
    public function getPlayersByTeamIndex(): array
    {
        $teamPlayers = [];
        foreach ($this->matchPlayers as $matchPlayer) {
            $teamPlayers[$matchPlayer->getTaskForce()][] = $matchPlayer;
        }
        return $teamPlayers;
    }
}

src/Controller/MatchController.php
<?php

namespace App\Controller;

use App\Entity\MatchPlayer;
use App\Mapper\MatchMapper;
use App\Repository\MatchPlayerRepository;
use App\Service\PlayerService;
use App\Service\SmiteService;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class MatchController extends AbstractController
{
    /** @var EntityManagerInterface */
    protected $entityManager;

    /** @var LoggerInterface */
    protected $logger;

    /** @var MatchMapper */
    protected $matchMapper;

    /** @var PlayerService */
    protected $playerService;

    /** @var SmiteService */
    protected $smiteService;

    public function __construct(
        EntityManagerInterface $entityManager,
        LoggerInterface $logger,
        MatchMapper $matchMapper,
        PlayerService $playerService,
        SmiteService $smiteService
    ) {
        $this->entityManager = $entityManager;
        $this->logger = $logger;
        $this->matchMapper = $matchMapper;
        $this->playerService = $playerService;
        $this->smiteService = $smiteService;
    }

    /**
     * @Route("/matches/", name="matches")
     * @param int id
     * @return Response
     */
    public function index(): Response
    {
        $matchPlayerRepo = $this->entityManager->getRepository(MatchPlayer::class);

        /** @var MatchPlayerRepository $matchPlayerRepo */
        $latestMatchIdsArray = $matchPlayerRepo->getLatestMatchIds(10);
        $latestMatchIds = array_column($latestMatchIdsArray, 'smiteMatchId');

        $matchPlayers = $matchPlayerRepo->getMatchPlayersByIds($latestMatchIds);
        $matches = $this->matchMapper->to($matchPlayers);

        return $this->render('matches/index.html.twig', [
            'matches' => $matches
        ]);
    }

    /**
     * @Route("/matches/{id}", name="match_view")
     * @param int id
     * @return Response
     */
    public function view(int $id): Response
    {
        $matchPlayerRepo = $this->entityManager->getRepository(MatchPlayer::class);
        $matchPlayers = $matchPlayerRepo->findBy(['smiteMatchId' => $id]);
        if (empty($matchPlayers)) {
            throw new NotFoundHttpException();
        }

        $matches = $this->matchMapper->to($matchPlayers);
        $match = reset($matches);

        return $this->render('matches/match.html.twig', [
            'match' => $match
        ]);
    }
}

templates/matches/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Latest Matches - Smite Stats - Unofficial SMITE{% endblock %}

{% block header_meta %}
    <link rel="canonical" href="https://smitestats.com/matches/" />
{% endblock %}

{% block body %}

    <div class="bg-light pt-3 pb-5">
        <div class="container">

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ path('homepage') }}">Home</a></li>
                    <li class="breadcrumb-item active">Matches</li>
                </ol>
            </nav>

            <div class="row">
                <div class="col-12">
                    <h1>Latest Smite Matches</h1>

                    {% for match in matches %}
                    <div class="card mb-3 box-shadow">

                        <div class="card-header">
                            <span class="d-inline-block">
                                <strong>{{ match.matchType }}</strong> |
                                {{ match.date|date }} |
                                <strong>{{ match.minutes }}</strong> minutes
                            </span>
                            <a class="btn btn-sm btn-primary float-right" href="{{ path('match_view', {id: match.smiteMatchId}) }}">View full match report</a>
                        </div>

                        <div class="card-body">
                            <div class="row mt-1">

                                {% for taskforceId, matchPlayers in match.playersByTeamIndex %}
                                <div class="col-xs-12 col-sm-6">
                                    <table class="stats-table table table-sm table-striped mb-0 {% if taskforceId == match.winningTaskforce %}border-success{% else %}border-danger{% endif %}">
                                        <tbody>
                                        {% for matchPlayer in matchPlayers %}
                                            <tr>
                                                <td>
                                                    {% if match.winningTaskforce == taskforceId %}
                                                        <span class="p-1 rounded bg-success"><strong>W</strong></span>
                                                    {% else %}
                                                        <span class="p-1 rounded bg-danger"><strong>L</strong></span>
                                                    {% endif %}
                                                </td>
                                                <td>
                                                    <div class="player-smite-god player-smite-god-small" style="background-image: url('https://web2.hirez.com/smite/god-cards/{{ matchPlayer.ReferenceName|slug }}.jpg')"></div>
                                                </td>
                                                <td>
                                                    {% if matchPlayer.smitePlayer and matchPlayer.smitePlayer.name|clan_remove|slug %}
                                                        <a class="d-inline-block" href="{{ path('player_view', {
                                                            gamertag: matchPlayer.smitePlayer.name|clan_remove|slug,
                                                            id: matchPlayer.smitePlayer.smitePlayerId
                                                        }) }}" title="Smite Player {{ matchPlayer.smitePlayer.name }}">{{ matchPlayer.smitePlayer.name }}</a>
                                                    {% else %}
                                                        <span class="d-inline-block">Unknown</span>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}

                                        </tbody>
                                    </table>

                                </div>
                                {% endfor %}

                            </div>

                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>

        </div>
    </div>

{% endblock %}